code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension bradlc.vscode-tailwindcss
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension CodeSandbox-io.codesandbox-projects
code --install-extension cpylua.language-postcss
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EliverLara.andromeda
code --install-extension esbenp.prettier-vscode
code --install-extension expo.vscode-expo-tools
code --install-extension fisheva.eva-theme
code --install-extension formulahendry.auto-rename-tag
code --install-extension fractalbrew.backticks
code --install-extension helixquar.randomeverything
code --install-extension lllllllqw.jsdoc
code --install-extension mattpocock.ts-error-translator
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension miguelsolorio.symbols
code --install-extension ms-python.autopep8
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension Orta.vscode-twoslash-queries
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension SumitSaha.learn-with-sumit-theme
code --install-extension svelte.svelte-vscode
code --install-extension tal7aouy.icons
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension vunguyentuan.vscode-postcss
code --install-extension WallabyJs.console-ninja
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wware.snippet-creator
code --install-extension yoavbls.pretty-ts-errors
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension bradlc.vscode-tailwindcss
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension CodeSandbox-io.codesandbox-projects
code --install-extension cpylua.language-postcss
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EliverLara.andromeda
code --install-extension esbenp.prettier-vscode
code --install-extension expo.vscode-expo-tools
code --install-extension fisheva.eva-theme
code --install-extension formulahendry.auto-rename-tag
code --install-extension fractalbrew.backticks
code --install-extension helixquar.randomeverything
code --install-extension lllllllqw.jsdoc
code --install-extension mattpocock.ts-error-translator
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension miguelsolorio.symbols
code --install-extension ms-python.autopep8
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension Orta.vscode-twoslash-queries
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension SumitSaha.learn-with-sumit-theme
code --install-extension svelte.svelte-vscode
code --install-extension tal7aouy.icons
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension vunguyentuan.vscode-postcss
code --install-extension WallabyJs.console-ninja
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wware.snippet-creator
code --install-extension yoavbls.pretty-ts-errors
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension bradlc.vscode-tailwindcss
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension CodeSandbox-io.codesandbox-projects
code --install-extension cpylua.language-postcss
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EliverLara.andromeda
code --install-extension esbenp.prettier-vscode
code --install-extension expo.vscode-expo-tools
code --install-extension fisheva.eva-theme
code --install-extension formulahendry.auto-rename-tag
code --install-extension fractalbrew.backticks
code --install-extension helixquar.randomeverything
code --install-extension lllllllqw.jsdoc
code --install-extension mattpocock.ts-error-translator
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension miguelsolorio.symbols
code --install-extension ms-python.autopep8
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension Orta.vscode-twoslash-queries
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension SumitSaha.learn-with-sumit-theme
code --install-extension svelte.svelte-vscode
code --install-extension tal7aouy.icons
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension vunguyentuan.vscode-postcss
code --install-extension WallabyJs.console-ninja
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wware.snippet-creator
code --install-extension yoavbls.pretty-ts-errors
